FREQUENCY_REQUESTS = 500
FREQUENCY_INTERVALS = 10
NULLPARAM_URLS = ['/','/account','/account/orders','/helpcentre','/account/flipkartfirst','/gift-voucher-balance','/account/wallet','/account/carddetails','/account/rewards','/profile','/wishlist','/account/changepassword','/account/addresses','/account/profilesettings','/account/accountemailupdate','/account/deactivate','/notifications','/account/subscriptions']
GEO = 950.0
AWS = 900.0
AZURE = 900.0
TOR = 800.0
NULLPARAM = 850.0
USERAGENT = 800.0
BADGOOGLEBOT = 900.0
FLAG_BOT_SCORE = 300.0
EXPIRE_SCORE_TIME = 15 * 60 * 1000
